PYTHON = python3
run:
	@pip install numpy
	@pip install pandas
	@pip install pickle-mixin
	@pip install matplotlib
	@pip install gensim
	@${PYTHON} Question_1.py
	@${PYTHON} Question_2_preprossesing.py
	@${PYTHON} Question_3d.py
	
	
	